version: 2
updates:
  package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "monthly"
  assignees:
    - 'kirill-oleynik'
  package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  assignees:
    - 'kirill-oleynik'
