# this file defines how to create image for app
FROM ruby:2.7-alpine

ENV APP_PATH /var/multiexpopeople
ENV BUNDLER_VERSION 2.1.4
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_PORT 3000

# copy entrypoint scripts and grant execution permissions
COPY ./dev-docker-entrypoint.sh /usr/local/bin/dev-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh

# install dependencies for application
RUN apk update && apk add libffi-dev build-base  \
  libc-dev linux-headers libxml2-dev nodejs tzdata git postgresql-dev

RUN rm -rf /var/cache/apk/* && mkdir -p $APP_PATH


RUN gem install bundler --version "$BUNDLER_VERSION" \
&& rm -rf $GEM_HOME/cache/*

# navigate to app directory
WORKDIR $APP_PATH

COPY Gemfile Gemfile.lock ./

# RUN bundle install

EXPOSE $RAILS_PORT

ENTRYPOINT [ "bundle", "exec" ]
