default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: MultiExpoPeople_development
  username: postgres
  password: password
  host: multiexpopeople_db
  port: 5432

test:
  <<: *default
  database: MultiExpoPeople_test
  username: postgres
  password: password
  host: multiexpopeople_db
production:
  <<: *default
  database: MultiExpoPeople_production
  username: MultiExpoPeople
  password: <%= ENV['MULTIEXPOPEOPLE_DATABASE_PASSWORD'] %>
